### ISSUE TITLE
Can’t delete save files if restored to new uninitialized user save slot

### ISSUE THREAD

**Issue by grockk** [Xpl0itU/savemii#26]
I did some testing a few months ago with Savemii and restored a save file to a different user slot that had no previous save. It worked fine and moved on. 

I just migrated to a larger HDD but couldn’t move this specific title. Gives error 160-2705. Everything else moved fine. Including games where I overwrote existing saves. I was able to copy the game and files but still couldn’t delete.  It just said failed to delete. But move always gave the above error. 

Since I was able to copy no data was lost, but I worry about someone restoring a save file to NAND that they may not be able to delete.

Interestingly the save file showed no date in data management. I’m not sure if this is a problem with Savemii or just doesn’t work to create new save files and should only be used to overwrite when restoring. Maybe it’s a permissions thing. Checkpoint has similar restriction on 3DS so maybe make a check not to allow restore unless an existing save has been initialized. I’ve reformatted the old drive so I’m not sure how much help I can give.

**Comment by Xpl0itU** [comment]
I doubt it’s a permissions issue, not sure what could cause this, might investigate

**Comment by GabyPCgeeK** [comment]
You can delete it using a ftp server or file manager.
I've investigated this a little and from what I remember it is a owner, group and possibly quota and folder/file structure problem.
From what I remember to initialize the save structure you need to:
- create folder structure
- copy tga and meta.xml
- create quota using the number account_save_size from xml
- change owner to lower 32 bits of title_id in xml and change group to group_id in xml

From what I remember for the vWii it doesn't have quota and the owner and group are calculated differently (I don't think I was able to find how to calculate/find them)

For my savemii mod I was able to make a prototype that worked for one game and was able to delete the save using data management. I never released it because it needed to incorporate a modded version of mocha that exposed the quota and owner functions and a lot of testing was needed to make sure it didn't caused bricks.

WUT seems to expose all the FSA functions so I'll try to add the save initialization to this version. If no one does it before me I'll probably have a prototype in one to four months.

**Comment by Xpl0itU** [comment]
> copy tga and meta.xml
create quota using the number account_save_size from xml

Been experimenting with this, thing is, how would you get the tga and meta.xml if they're not copied by savemii? Are they direct copies of the ones inside the title's meta folder?

**Comment by GabyPCgeeK** [comment]
You would need to have the game installed (I think game updates also have it) or game disk inserted. It would also be a good idea to backup those files once to the game folder where the slot folders reside so that way the saves can be restored without the game installed.

**Comment by Xpl0itU** [comment]
Been doing some great progress, currently:

- The savedata is detected by save management but it can't be deleted and it lacks a date (probably because of the missing saveinfo.xml)

You can check the progress here:
[https://github.com/Xpl0itU/savemii/blob/fixNotInit/src/savemng.cpp#L941](https://github.com/Xpl0itU/savemii/blob/fixNotInit/src/savemng.cpp#L941)

**Comment by Xpl0itU** [comment]
Fixed in 1.5.7
