### ISSUE TITLE
[Bug] I Cant load in Wii U Save Management (Freezes my Wii u)

### ISSUE THREAD

**Issue by SawderMC** [Xpl0itU/savemii#40]
I loaded the app fine on the first try (including the Wii U save Management) I rushed too quickly and tried to do a backup of my game without a save file and I thought it would still work. Obviously it didn't so I went and played the game for a bit to create a save file for it. Now when I go on SaveMii everything works fine I can go on vWii Save Management and I see my title no problem. But when I click on Wii U Save Management It freezes my console and I need to shut it off manually. I've tried a batch backup and I get a red screen that says failed backup. I've also tried troubleshooting on my end I removed all the files the app created and put back a fresh install same issue. I reformatted my sd card and put back all of my files into it nothing works. Hopefully someone knows what I can do to fix this appreciate any advice that could come my way. Thanks and have a blessed day <3

**Comment by jmvlr** [comment]
I had a similar experience, but don't know if it will be the same issue. Could still be related and worth investigating though.

I found out that if you have a disc inserted into the console (it was Smash in my case), you moved the game's save file to an external USB beforehand, and that specific USB with the save file isn't attached to the WiiU at the moment this SaveMii port is loaded, then the console will freeze when trying to display the game title within the WiiU Save Management list of titles.

BUT, if a different USB drive is connected, it will straight up freeze immediately after clicking on WiiU Save Management (which could be the issue @SawderMC is having?).

The workaround then, in my case, was simply ejecting the disc before running SaveMii.

I've only tested that with this specific SaveMii fork, but it could perfectly be an issue with other SaveMiis too.

**Comment by OldGnashburg** [comment]
I'm having this issue on Aroma too. But having no disc wouldn't fix this issue. Just freezes right away.

**Comment by w3irDv** [comment]
Give this a try: https://github.com/Xpl0itU/savemii/releases/tag/1.6.3. It solves a problem during the initialization that is not the one @jmvlr  and @SawderMC are reporting, but may be it can help to avoid it.  With this build I see the problem: an extra title (only the numeric id, not the name) corresponding to the inserted disc appears in the list of Wii U titles it. This entry can cause corruption, because the app doesn't know how to parse it. In my cases the app has not crashed, but maybe it's just good luck. Anyway, I'll add a new condition in the next release to avoid the problem.
@OldGnashburg, if your problem is caused by installed titles with saves in the nand and in the usb, this release should fix it.

**Comment by OldGnashburg** [comment]
Issue seems resolved for me now. I did fresh installs of everything and am on a SDUSB setup now. It was annoying process but it works now

**Comment by w3irDv** [comment]
Thanks @OldGnashburg for your feedback.

**Comment by w3irDv** [comment]
Code fixed to prevent a title inserted in the disc to be added to the gamelist. Preview here: https://github.com/Xpl0itU/savemii/actions/runs/10586515866. Will be added to 1.6.4.
