### ISSUE TITLE
App doesn't load on Wii U with latest update

### ISSUE THREAD

**Issue by dingdong42564** [Xpl0itU/savemii#64]
When launching the app, it freezes or gets stuck on the loading screen (the large save icon with white background) and nothing happens. I downloaded the app from the homebrew store and is updated to the latest version (1.6.3). Additionally, pressing the home button does nothing. 

Edit:
https://github.com/Xpl0itU/savemii/issues/64#issuecomment-2342070050

**Comment by w3irDv** [comment]
Hello @dingdong42564 , so the 1.6.3 version never goes beyond of the initial screen with the  big save icon screen? Never changes to black? If so, its failing just in the different initialization processes, without even trying to read any title from the Wii U. I'll need some more information to try to understand what is happening, Are you trying the app from Aroma or from Tiramisu? (If applies) Which version of Aroma ? Does your console has ISFSHax? Does the previous version (1.6.1) work ok? This week I have limited connectivity to the internet, but if the problem is still happening, next week I can take a look.

**Comment by dingdong42564** [comment]
Im currently on the latest version of Aroma and not using isfshax.  I have not tested the previous version but I will try it sometime later.

**Comment by w3irDv** [comment]
Hi! Can you share  how you solve your issue? May be is useful to other
users (so far noone has complained, but just in case)

Thanks!.

**Comment by dingdong42564** [comment]
Honestly, I don't know how it started working randomly. But, I think it's because my SD card was completely full, so when I made some space on it, it loaded as normal.

**Comment by w3irDv** [comment]
Thanks for the feedback!
